### ISSUE TITLE
[CONTRIB-4286] Codechecker don't correctly identify escaped $ in strings

### ISSUE THREAD

**Issue by sarjona** [moodlehq/moodle-cs#10]
While working on cleaning all styling issues under question/format/ for MDL-39404, the codechecker wrongly reported the line
`$expout .= "\$CATEGORY: $question->category\n";
`
in the question/format/gift/format.php as containing a mistake with the message:
`Member variable "CATEGORY" must be all lower-case
`

---
Reporter: Jean-Michel Vedrine
Original issue: https://tracker.moodle.org/browse/CONTRIB-4286

**Comment by jrchamp** [comment]
This bug still exists and is part of the `moodle.NamingConventions.ValidVariableName.VariableNameLowerCase` sniff.
