### ISSUE TITLE
"Missing member variable doc comment" in the constructor arguments that are class properties

### ISSUE THREAD

**Issue by marinaglancy** [moodlehq/moodle-cs#150]
```
~/repositories/moodle-plugin-ci/vendor/bin/phpcs mod/lti/classes/output/course_tools_page_header.php

FILE: /.../mod/lti/classes/output/course_tools_page_header.php
----------------------------------------------------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------
 38 | ERROR | Missing member variable doc comment
 38 | ERROR | Missing member variable doc comment
 38 | ERROR | Missing member variable doc comment
----------------------------------------------------------------------------------------------------------------
```

This is the code of the respective file:
https://github.com/moodle/moodle/blob/v4.3.3/mod/lti/classes/output/course_tools_page_header.php#L31-L39

```
    /**
     * Constructor.
     *
     * @param int $courseid the course id.
     * @param int $toolcount the number of tools available in the course.
     * @param bool $canadd whether the user can add tools to the course or not.
     */
    public function __construct(protected int $courseid, protected int $toolcount, protected bool $canadd) {
    }
```

This is different from https://github.com/moodlehq/moodle-cs/issues/142 because the arguments have the word "protected" in front of them, which makes them class properties

**Comment by andrewnicols** [comment]
The Sniff is correct -- the variables are not documented.

```php
 /**
     * Constructor.
     *
     * @param int $courseid the course id.
     * @param int $toolcount the number of tools available in the course.
     * @param bool $canadd whether the user can add tools to the course or not.
     */
    public function __construct(
        /** @var int ID of the course */
        protected int $courseid,
        /** @var int The number of tools */
        protected int $toolcount,
        /** @var  bool Whether the user can add tools to the course */
        protected bool $canadd.
    ) {
    }
```

**Comment by marinaglancy** [comment]
Thanks Andrew,

btw this syntax fails in the previous version (using local_moodlecheck) which is quite annoying but we can't really change it

**Comment by daniil-berg** [comment]
@andrewnicols Just to be clear, it is intentional that adherents to this code style are expected to document _both_ the parameters in the doc block above _and_ the properties in individual doc blocks, even though constructor promotion makes them the same thing? Is the reasoning behind this that while the constructor parameter is automatically promoted to a property here, there may still be _additional_ logic inside the constructor applied to the parameter/property that may or may not be worth documenting? If so, wouldn't it be possible to only enforce this for non-empty constructors?
