### ISSUE TITLE
Unable to pass checks with multiline attributes using MissingDocblockSniff for non-class methods

### ISSUE THREAD

**Issue by ziegenberg** [moodlehq/moodle-cs#185]
The following file fails with an error messages:

-  Missing docblock for function `single_method_multiline_attribute`

```php
<?php
/*
 * Function with multiline attributes.
 */
#[someattribute(
    attr1: 'asdf',
    attr2: 'asdf',
)]
function single_method_multiline_attribute(): void {
}
```

Also see: https://integration.moodle.org/job/Precheck%20remote%20branch/164248/artifact/work/smurf.html#phpcs

**Comment by ziegenberg** [comment]
Yeah, I will close this one again. It was a false positive...

**Comment by andrewnicols** [comment]
For anyone wondering why thi sis a false positive:

```php
/*
 * Test.
 */
```

vs.

```php
/**
 * Test.
 */
```

**Comment by ziegenberg** [comment]
This sneaky little missing asterisk. It took me an hour to find it. And some debugging. 🙈
