### ISSUE TITLE
Deprecated: Creation of dynamic property MoodleHQ\MoodleCS\moodle\Sniffs\ControlStructures\ControlSignatureSniff::$supportedTokenizers is deprecated in /Applications/MAMP/htdocs/moodle/mod/tutoom/vendor/moodlehq/moodle-cs/moodle/Sniffs/ControlStructures/ControlSignatureSniff.php on line 38

### ISSUE THREAD

**Issue by jimmy-sandoval** [moodlehq/moodle-cs#38]
Hi, I'm new around here.

I am installing moodlehq/moodle-cs in my plugin version 3.3.0 and it gives me problems. In each file that I try to save, it generates a log at the top:

```php
Deprecated: Creation of dynamic property MoodleHQ\MoodleCS\moodle\Sniffs\ControlStructures\ControlSignatureSniff::$supportedTokenizers is deprecated in /Applications/MAMP/htdocs/moodle/mod/tutoom/vendor/moodlehq/moodle-cs/moodle/Sniffs/ControlStructures /ControlSignatureSniff.php on line 38
```

Screenshot:
![image](https://user-images.githubusercontent.com/86315081/212393056-81b64153-3b1a-477a-9f22-ed612d220e5a.png)

This is my composer.json
```json
{
  "require": {
    "squizlabs/php_codesniffer": "*",
    "moodlehq/moodle-cs": "^3.3"
  },
  "require-dev": {
    "phpcompatibility/php-compatibility": "dev-develop",
    "dealerdirect/phpcodesniffer-composer-installer": "^0.7.2"
  },
  "config": {
    "allow-plugins": {
      "dealerdirect/phpcodesniffer-composer-installer": true
    }
  }
}
```

And another problem or warnign:

Location: vendor/moodlehq/moodle-cs/moodle/Util/MoodleUtil.php
![image](https://user-images.githubusercontent.com/86315081/212393695-6dd74ca8-013d-4a81-8821-a96c5b29af2b.png)

**Comment by stronk7** [comment]
Hi @jimmy-sandoval ,

thanks for the report. This was fixed some time ago (the 2 problems) by this commit:

https://github.com/moodlehq/moodle-cs/commit/702e30bf5028b77bf3f9b2ad981d09151990fcde

So I'm going to close this now. Ciao :-)
