### ISSUE TITLE
Ensure that dataProvider sniffs point to the line where problems are happening

### ISSUE THREAD

**Issue by stronk7** [moodlehq/moodle-cs#72]
This is a copy from https://tracker.moodle.org/browse/CONTRIB-9387, originally reported by @kordan.

It seems that the dataProvider sniffs (recently introduced), whenever they find a problem (missing static, missing/incorrect return type...) they are reporting the line where the `@dataProvider` tag is, instead of the line where the data provider declaration (and errors) happen.

That's a little bit misleading / confusing when looking for errors, wrongly making you think that the problem is in the phpdoc tag.

We should point to the real line where the problem is (data provider function declaration, normally).

Ciao :-)

**Comment by kordan** [comment]
Great. Thank you.
