### ISSUE TITLE
Make all test case classes having test_xxxx methods final

### ISSUE THREAD

**Issue by stronk7** [moodlehq/moodle-cs#74]
Slightly related (discussed at) #71 , we should make all test case classes having "test_xxxx" methods to be explicitly `final`.

That way we forbid extending them by mistake, and getting things double-executed without notice.

I read about this recently, when looking to some PHPUnit 10 stuff and it makes complete sense for me as a good practice (in fact, examples @ PHPUnit docs have the `final` since versions ago (very same than return types).

Ciao :-)

**Comment by andrewnicols** [comment]
@paulholden All test classes which have a test method will be final, but really it should be _all_ test classes because we should only ever extend a testcase class.

**Comment by stronk7** [comment]
(snap!) :)

**Comment by paulholden** [comment]
OK, I misread this line:

> Slightly related (discussed at) https://github.com/moodlehq/moodle-cs/pull/71 , we should make all test case classes having "test_xxxx" methods to be explicitly final.

You're talking about making the _class_ final, not each _method_ - makes sense
